### ISSUE TITLE
Cloud exporter publication roadmap

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1191]
with @icarito 

* [x] 1) Merge new custom LDI export API (https://github.com/publiclab/Leaflet.DistortableImage/pull/485/)
* [x] 2) publish version 0.10.0 and pull into MapKnitter (https://github.com/publiclab/mapknitter/pull/1192)
* [x] 3) get status URLs saving again in export model: https://github.com/publiclab/mapknitter/issues/1190  (https://github.com/publiclab/mapknitter/pull/1192)
* [x] 4) save map id, user id in export model!!!! LOL (https://github.com/publiclab/mapknitter/pull/1192)
* [x] 5) display list of exports run with their status.json url (https://github.com/publiclab/mapknitter/pull/1192)
* [x] 6) parse the status.json to display export products (JS so it's reusable) (#326 and #814  related) (https://github.com/publiclab/mapknitter/pull/1192)
* [x] 7) test on unstable - http://mapknitter-unstable.laboratoriopublico.org/maps/test4/edit (sebastian may need to fix unstable)
* [x] 8) test on stable - https://stable.mapknitter.org/maps/testmap/edit
* [x] 9) PUBLISH MAPKNITTER
* [x] 10) intro the new system
* [x] 11) hide the old export button, AND the "exports" dropdown
* [x] 12) display previous export products from old exporter (example https://mapknitter.org/maps/yaffa/ -- just fallback if no `status.json` to https://mapknitter.org/export/status/10129?) (DONE: https://github.com/publiclab/mapknitter/commit/e6b280d5f41e0768d3838a53dc1887a9e5f8f449)
* [x] 13) move it to Cloud container
* [x] 14) PUBLISH MAPKNITTER

BASIC FUNCTIONALITY DONE HERE!!! 🎉 

* [ ] free up Rackspace

## Follow-ups

* [x] add a progress bar
* [x] get exports listing to auto-refresh
* [x] style exports on map view page
* [x] load test it
* [x] better UI to initiate exports
* [x] ensure starting a 2nd export works
* [ ] 14) add `image-sequencer-app` export option: https://github.com/publiclab/image-sequencer-app/issues/19#issuecomment-606833260
* [ ] figure out runtime calculation and stats like # of images
* [ ] ensure canceling works

**Comment by jywarren** [comment]
And ref #1128

**Comment by jywarren** [comment]
We prob need to get unstable server connected to Amazon S3!

**Comment by jywarren** [comment]
Noting critical issue for starting a second export via @sashadev-sky - https://github.com/publiclab/Leaflet.DistortableImage/issues/522

Thanks!

**Comment by jywarren** [comment]
I was able to change the src attributes of images in the dev console and get an export to run from local!

**Comment by jywarren** [comment]
And need to make Free Rotate the "r"

**Comment by jywarren** [comment]
Some follow-ups:

* [ ] allow deleting old exports (that did not succeed?)
* [ ] get exports listing to update when a new one is generated (using a partial and an update)
* [ ] clean up display of exports: show spinner for in-progress
* [ ] get exports listing to refetch status.json periodically

**Comment by jywarren** [comment]
still need to make "free rotate" be the "r" key i think...

**Comment by icarito** [comment]
Hi, just checking if there's been the required testing or what is blocking this. If there's any way I can be useful please direct me. I can see that it doesn't seem to work well but I'm unsure of how it is supposed to work.

**Comment by jywarren** [comment]
Ok, so we need to do some multi image testing on 

https://stable.mapknitter.org/maps/testmap/edit

Then we can publish to production and ask folks to do broader testing! Then... Some UI refinements.

**Comment by icarito** [comment]
Yes! It seems to work, and fast, for many images: 
![](https://mapknitter-exports-warps.storage.googleapis.com/1585430085/1585430085.jpg)

This one is from https://stable.mapknitter.org/maps/vibora2/edit

The UI does need some work! Also several warnings on the Javascript console to fix too.

**Comment by jywarren** [comment]
Testing out at https://github.com/publiclab/mapknitter/issues/1244

**Comment by jywarren** [comment]
We are now ready to publish to production with the legacy exporter offline, and test moving this to a container!

**Comment by jywarren** [comment]
cc @icarito -- we can test the current `main` branch in a Google Cloud container now as it no longer has legacy in-app exporting offered. 🎉

**Comment by icarito** [comment]
That is awesome, I'll look into it today!

**Comment by alaxalves** [comment]
Linking https://github.com/publiclab/mapknitter/pull/1273

**Comment by jywarren** [comment]
Re-opening to track follow-ups!
